fileobject = open("practice.txt", "w")
str = "My name is Jeslin Marium Alex.Iam from Thiruvalla."
fileobject.write(str)
fileobject = open("practice.txt", "r")
print('Initially,the position of the file object is:', fileobject.tell())
str = fileobject.read()
print(str)
print("The position of the file object is :", fileobject.tell())
fileobject.seek(5, 0)
print("Now  the file object is at of the file :", fileobject.tell())
str=fileobject.read()
print(str)
fileobject.seek(30)
print("The position of the file object is at:", fileobject.tell())
str = fileobject.read()
print(str)
fileobject.close()
